### PR TITLE
created AUTHORS file

### PR DESCRIPTION
**Pull request by soham1sawant**
This file is to display the names of all the awesome people who have contributed to this project. People who have a successful merge of their pull request should add their name in the AUTHORS file if its not already there.

### CODE REVIEW

**Comment by BenjaminCCross** [comment]
I believe Github keeps track of this for us

**Comment by robsmithw** [comment]
I think this is a good idea, but as mentioned by @BenjaminCCross github already tracks this for us.
image

**Comment by BrianRuizy** [comment]
I've made a pull request which showcases the contributors on the README.md.
I don't believe it is entirely necessary to make a file for that.
Check here: #37.

**Comment by robsmithw** [comment]
@soham1sawant Probably a good idea to decline this PR now that we can track it in #37 in order to keep our PR's clean.

**Comment by soham1sawant** [comment]
Yes will do that

**Comment by soham1sawant** [comment]
Deleted as contributors are mentioned in the README

**Pull request closed without merging**
