### PR TITLE
added html xd css

### PR DESCRIPTION
**Pull request by novibonjovi**
Hey, here is the .xd design file.
I also started working on the html and css, I'm pretty new to it though.

### CODE REVIEW

**Comment by diepoe** [comment]
What frontend have you used?

**Comment by diepoe** [comment]
*framework

**Comment by novibonjovi** [comment]
Its just scss/css and html

**Comment by diepoe** [comment]
because i saw nothing, but now it's working

**Comment by erik-gross-hardt** [comment]
@novibonjovi It would be very kind of you, if you could also provide some screenshots.

**Comment by novibonjovi** [comment]
image

image

Here are two screenshots.
My pull request is pretty bad, i didn't know at the time how to push to a repository properly.
When i have time ill try to break the code down and push it properly.

**Comment by erik-gross-hardt** [comment]
@novibonjovi Sorry maybe I should have explained myself more clearly I meant screenshots of the UI you have made sorry for inconvinience.

**Comment by novibonjovi** [comment]
image

Heres a screenshot of the UI in adobe xd.

**Pull request merged**
