### PR TITLE
Add checks, forgotPassword Model and updated user/event model

### PR DESCRIPTION
**Pull request by JannesT3011**
Add checks for username, password and email + add 'username' to event/user model

### CODE REVIEW

**Review by eliemugenzi — APPROVED** [review]

**Comment by 0x7081** [comment]
Why didn't you use the model.Model class for creating models?

**Comment by JannesT3011** [comment]
Thats a good hint, thanks. I'll rewrite the models.

**Comment by JannesT3011** [comment]
But the django model.Model class is only for database, right? Or can you define a type with them?

**Comment by 0x7081** [comment]
Oh you are right.
I forgot we use firebase for the backend, I would still prefer a database but that's discussed in another issue.

**Pull request merged**
